version: '3'

services:
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    networks:
      prom-net:
        aliases:
          - zipkin
      reddit:
        aliases:
          - zipkin
    ports:
      - "9411:9411"

  fluentd:
    image: ${USER_NAME}/fluentd
    container_name: fluentd
    ports:
      - "24224:24224"
      - "24224:24224/udp"

  elasticsearch:
    image: elasticsearch:5.6
    container_name: elasticsearch
    expose:
      - 9200
    ports:
      - "9200:9200"

  kibana:
    image: kibana:5.6
    container_name: kibana
    ports:
      - "5601:5601"
