kind: EncryptionConfig
apiVersion: v1
resources:
  - resources:
      - secrets
    providers:
      - aescbc:
          keys:
            - name: key1
              secret: wAPAPBiSG4eqVlI25Z+BTMyvGXiJv+C+55ZyTJH1rj4=
      - identity: {}
